# Generated by Django 5.1.6 on 2025-02-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('created_datetime', models.DateTimeField()),
                ('modified_datetime', models.DateTimeField()),
                ('size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=255)),
                ('parent_folder', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('document_date', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.filemetadata')),
            ],
        ),
    ]
